name: compliance-check

on:
  repository_dispatch:
    types: [socialgouv-bot]

jobs:
  register-and-lint:
    runs-on: ubuntu-latest
    steps:

    - run: echo "It Works!"

    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
