name: compliance-check

on:
  repository_dispatch:
    types: [socialgouv-bot]

jobs:
  register-and-lint:
    runs-on: ubuntu-latest
    steps:

    # - run: echo "It Works!"

    # - uses: SvanBoxel/organization-workflow@main
    #   with:
    #     id: ${{ github.event.client_payload.id }}
    #     callback_url: ${{ github.event.client_payload.callback_url }}
    #     sha: ${{ github.event.client_payload.sha }}
    #     run_id: ${{ github.run_id }}
    #     name: ${{ github.workflow }}

    - name: Register workflow run to SocialGouv application
      run: |
        curl -G \
          "${{ github.event.client_payload.callback_url }}" \
          -d id=${{ github.event.client_payload.id }} \
          -d runId=${{ github.run_id }} \
          -d sha=${{ github.event.client_payload.sha }} \
          -d repoOwner=${{ github.event.client_payload.repository.owner }} \
          -d repoName=${{ github.event.client_payload.repository.name }} \
          -d enforce=false \
          -d enforce_admin=false \
          --data-urlencode "name=${{ env.name || github.workflow }}" \
          --data-urlencode "documentation=.github/workflows/compliance-info.md"
